---
title: "Questão 3"
author: "Mário/Rodney"
date: "April 6, 2017"
output: pdf_document
---

Questão 3:

Item a:
```{r}
# densidade Epanechnikov
d_epach = function(x) 3*(1 - x^2)/4
# função para gerar variáveis aleatórias com distribuição Epanechnikov
r_epach = function(n){
  v = rep(0,n)
  for(i in 1:n){
    u1 = runif(1,-1,1); u2 = runif(1,-1,1); u3 = runif(1,-1,1);
    if((abs(u3)>abs(u2))&&(abs(u3)>abs(u1))){
      v[i] = u2
    }else{
      v[i] = u3
    }
  }
  return(v)
}

# histograma de uma amostra da Epanechnikov e a densidade verdadeira
hist(r_epach(100000),prob=TRUE,main="Histograma - núcleo de Epanechnikov",
     ylim=c(0,1),ylab="Densidade",xlab="")
curve(d_epach, xlim=c(-1,1),add=TRUE,col=2,lwd=2)
```


Item b: Sabemos que $U_i \sim U(-1,1)$, $i\in\{1,2,3\}$, daí a função de distribuição de $U_i$ é 
$$
F_U(u) = \frac{u+1}{2},
$$
então, para $Y_i = |U_i|$ temos que
$$
F_{Y_i}(y) = P(|U_i| \leq y) = P(-y \leq U_i \leq y) = F_{U_i}(y) - F_{U_i}(-y) = \left(\frac{y+1}{2}\right) - \left(\frac{-y+1}{2}\right) = y,
$$
ou seja, $Y_i \sim U(0,1)$, $i\in\{1,2,3\}$.

Sendo $X$ a variável aleatória gerada de acordo com o algoritmo descrito, temos que
$$
X = \left\{\begin{array}{cc}
U_2 & \textrm{se } |U_3|>max\{|U_1|,|U_2|\}\\
U_3 & \textrm{se } |U_3|\leq max\{|U_1|,|U_2|\}\\
\end{array}\right.,
$$
e como $U_2$ e $U_3$ são simétricas em torno de zero, pelo algoritmo temos que $X$ também o será. Logo, $P(X<0) = 1/2$. Considerando então $0<x<1$, temos que
\begin{align*}
P(|X|\leq x) &= P(|U_3|>max\{|U_1|,|U_2|\},|U_2|\leq x) + P(|U_3|>max\{|U_1|,|U_2|\},|U_3|\leq x)\\
&= P(Y_3>max\{Y_1,Y_2\},Y_2\leq x) + P(Y_3>max\{Y_1,Y_2\},Y_3\leq x).
\end{align*}

Sabemos que a densidade de $Y_i$ é $f_{Y_i}(y) = 1$ para $0<y<1$. Assim, calculando a primeira probabilidade temos que
\begin{align*}
P(Y_3>max\{Y_1,Y_2\},Y_2\leq x) &= P(Y_1\leq Y_2 \leq Y_3, Y_2\leq x) + P(Y_2\leq Y_2 \leq Y_3, Y_2\leq x)\\\
&= \int_{0}^{x}\int_{0}^{y_2}\int_{y_2}^{1}dy_3dy_1dy_2 + \int_{0}^{x}\int_{y_2}^{1}\int_{y_1}^{1}dy_3dy_1dy_2\\
&= \int_{0}^{x}\int_{0}^{y_2}(1-y_2)dy_1dy_2 + \int_{0}^{x}\int_{y_2}^{1}(1-y_1)dy_1dy_2\\
&= \int_{0}^{x}(1-y_2)y_2dy_1dy_2 + \int_{0}^{x}\left[\left.(y_1-\frac{y_1^2}{2})\right|_{y_2}^{1}\right]dy_2\\
&= \left.\left(\frac{y_2^2}{2}-\frac{y_2^3}{3}\right)\right|_0^x + \int_{0}^{x}\left[1 - \frac{1}{2} - y_2 + \frac{y_2^2}{2} \right]dy_2\\
&= \frac{x^2}{2}-\frac{x^3}{3} + \left.\left[\frac{y_2}{2} - \frac{y_2^2}{2} + \frac{y_2^3}{6} \right]\right|_0^x\\
&= \frac{x^2}{2}-\frac{x^3}{3} + \frac{x}{2}-\frac{x^2}{2} + \frac{x^3}{6} = \frac{x}{2} - \frac{x^3}{6}\\
\end{align*}

Na segunda probabilidade, temos que
\begin{align*}
P(Y_3>max\{Y_1,Y_2\},Y_3\leq x) &= P(Y_3\leq Y_2 \leq Y_1, Y_3\leq x) + P(Y_2\leq Y_3 \leq Y_1, Y_3\leq x) \\
&+ P(Y_3\leq Y_1 \leq Y_2, Y_3\leq x) + P(Y_1\leq Y_3 \leq Y_2, Y_3\leq x)\\
&= 2[P(Y_3\leq Y_2 \leq Y_1, Y_3\leq x) + P(Y_2\leq Y_3 \leq Y_1, Y_3\leq x)],
\end{align*}
onde na primeira igualdade listamos as possíveis formas que o evento $[Y_3>max\{Y_1,Y_2\},Y_3\leq x]$ pode ocorrer e na segunda igualdade usamos o fato de $Y_1$ e $Y_2$ serem identicamente distribuídas. Daí
\begin{align*}
P(Y_3>max\{Y_1,Y_2\},Y_3\leq x) &= 2\left[ \int_{0}^{x}\int_{y_3}^{1}\int_{y_2}^{1}dy_1dy_2dy_3 + \int_{0}^{x}\int_{0}^{y_3}\int_{y_3}^{1}dy_1dy_2dy_3 \right]\\
&= 2\left[ \int_{0}^{x}\int_{y_3}^{1}(1-y_2)dy_2dy_3 + \int_{0}^{x}\int_{0}^{y_3}(1-y_3)dy_2dy_3 \right]\\
&= 2\left[ \int_{0}^{x}\left[\left.(y_2-\frac{y_2^2}{2})\right|_{y_3}^{1}\right]dy_3 + \int_{0}^{x}(1-y_3)y_3dy_3 \right]\\
&= 2\left[ \int_{0}^{x}\left[\frac{1}{2} - y_3 + \frac{y_3^2}{2}\right]dy_3 + \left.\left(\frac{y_3^2}{2}-\frac{y_3^3}{3}\right)\right|_0^x \right]\\
&= 2\left[ \left.\left[\frac{y_3}{2} - \frac{y_3^2}{2} + \frac{y_3^3}{6} \right]\right|_0^x + \frac{x^2}{2}-\frac{x^3}{3} \right]\\
&= 2\left[ \frac{x}{2} - \frac{x^2}{2} + \frac{x^3}{6} + \frac{x^2}{2}-\frac{x^3}{3} \right] = x - \frac{x^3}{3}\\
\end{align*}

Portanto,
$$
P(|X|\leq x) = \frac{x}{2} - \frac{x^3}{6} + x - \frac{x^3}{3} = \frac{3x}{2} - \frac{3x^3}{6} = \frac{3x - x^3}{2},
$$
e pela simetria de $X$, temos que 
$$
P(X\leq x) = P(X\leq 0) + P(0<X\leq x) = \frac{1}{2} + \frac{P(|X|\leq x)}{2} = \frac{1}{2} + \frac{3x - x^3}{4},
$$
onde $0<x<1$. Novamente usando o fato da distribuição de $X$ ser simétrica, temos para $0<x<1$ que
$$
F_X(-x) = 1 - F_X(x) = 1 - \left[ \frac{1}{2} + \frac{3x - x^3}{4} \right] 
= \frac{1}{2} - \frac{(3x - x^3)}{4} 
= \frac{1}{2} + \frac{3(-x) - (-x)^3}{4},
$$
ou seja, a função de distribuição de $X$ é $F_X(x) = 1/2 + (3x - x^3)/4$, para $x\in[-1,1]$, e derivando $F_X(x)$ em relação a $x$ obtemos a função densidade de $X$, que é
$$
f_X(x) = \frac{3(1-x^2)}{4}, \quad -1\leq x \leq 1,
$$
assim, vemos que $X$ tem distribuição Epanechnikov, e o método de geração está correto.
